repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff check
        entry: ruff check --fix
        language: system
        types_or: [python, pyi]
      - id: ruff-format
        name: ruff format
        entry: ruff format
        language: system
        types_or: [python, pyi]
      - id: mypy
        name: mypy
        entry: mypy src tests scripts
        language: system
        pass_filenames: false
        types_or: [python, pyi]
      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        types_or: [python, pyi]
      - id: uv-audit
        name: uv audit
        entry: uv --preview-features audit-command audit --frozen
        language: system
        pass_filenames: false
        always_run: true
